FROM debian:bullseye
MAINTAINER nickapos@oncrete.gr
EXPOSE 80
RUN apt-get update && apt-get -y upgrade && apt-get -y install php7.4 php7.4-curl php7.4-mysql php7.4-mbstring php7.4-xml git
CMD /bin/bash