#!/bin/bash
sudo chmod -R g+rw /var/www/html/cloudlog/application/config/
sudo chmod -R g+rw /var/www/html/cloudlog/assets/qslcard/
sudo chmod -R g+rw /var/www/html/cloudlog/backup/
sudo chmod -R g+rw /var/www/html/cloudlog/updates/
sudo chmod -R g+rw /var/www/html/cloudlog/uploads/
sudo chmod -R g+rw /var/www/html/cloudlog/images/eqsl_card_images/